inherit_gem:
  aaf-gumboot: aaf-rubocop.yml

Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3

# RC class is singular by design
# Will be reduced in the future
# when FR3 takes over admin features.
Metrics/ClassLength:
  Exclude:
    - app/rapid_connect.rb

Metrics/LineLength:
  Exclude:
    - app/rapid_connect.rb
    - spec/rapid_connect_spec.rb

Metrics/MethodLength:
  Exclude:
    - app/rapid_connect.rb

Metrics/AbcSize:
  Exclude:
    - app/rapid_connect.rb
