AllCops:
  Exclude:
    - db/schema.rb

# RC class is singular by design
# Will be reduced in the future
# when FR3 takes over admin features.
ClassLength:
  Enabled: false

LineLength:
  Enabled: false

MethodLength:
  Enabled: false
